--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/29/2020 5:50:28 AM
-- Server version: 8.0.20
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE ecomm_services;

--
-- Drop table `hibernate_sequence`
--
DROP TABLE IF EXISTS hibernate_sequence;

--
-- Drop table `cart_products`
--
DROP TABLE IF EXISTS cart_products;

--
-- Drop table `carts`
--
DROP TABLE IF EXISTS carts;

--
-- Drop table `order_products`
--
DROP TABLE IF EXISTS order_products;

--
-- Drop table `products`
--
DROP TABLE IF EXISTS products;

--
-- Drop table `orders`
--
DROP TABLE IF EXISTS orders;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `address`
--
DROP TABLE IF EXISTS address;

--
-- Set default database
--
USE ecomm_services;

--
-- Create table `address`
--
CREATE TABLE address (
  id bigint NOT NULL AUTO_INCREMENT,
  city varchar(255) DEFAULT NULL,
  country varchar(255) DEFAULT NULL,
  state varchar(255) DEFAULT NULL,
  street varchar(255) DEFAULT NULL,
  zip_code varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `users`
--
CREATE TABLE users (
  id bigint NOT NULL,
  email varchar(255) DEFAULT NULL,
  encoded_password varchar(60) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  phone_number varchar(255) DEFAULT NULL,
  address_id bigint DEFAULT NULL,
  cart_id bigint DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE users
ADD CONSTRAINT FKditu6lr4ek16tkxtdsne0gxib FOREIGN KEY (address_id)
REFERENCES address (id);

--
-- Create table `orders`
--
CREATE TABLE orders (
  id bigint NOT NULL,
  order_date datetime(6) DEFAULT NULL,
  total_price double DEFAULT NULL,
  user_id bigint DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT FK32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id)
REFERENCES users (id);

--
-- Create table `products`
--
CREATE TABLE products (
  id bigint NOT NULL AUTO_INCREMENT,
  description varchar(500) DEFAULT NULL,
  name varchar(60) DEFAULT NULL,
  price double DEFAULT NULL,
  stock int DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `order_products`
--
CREATE TABLE order_products (
  id bigint NOT NULL AUTO_INCREMENT,
  quantity int NOT NULL,
  order_id bigint DEFAULT NULL,
  product_id bigint DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE order_products
ADD CONSTRAINT FKawxpt1ns1sr7al76nvjkv21of FOREIGN KEY (order_id)
REFERENCES orders (id);

--
-- Create foreign key
--
ALTER TABLE order_products
ADD CONSTRAINT FKdxjduvg7991r4qja26fsckxv8 FOREIGN KEY (product_id)
REFERENCES products (id);

--
-- Create table `carts`
--
CREATE TABLE carts (
  id bigint NOT NULL,
  user_id bigint DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE carts
ADD CONSTRAINT FKb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id)
REFERENCES users (id);

--
-- Create foreign key
--
ALTER TABLE users
ADD CONSTRAINT FKdv26y3bb4vdmsr89c9ppnx85w FOREIGN KEY (cart_id)
REFERENCES carts (id);

--
-- Create table `cart_products`
--
CREATE TABLE cart_products (
  id bigint NOT NULL,
  quantity int NOT NULL,
  cart_id bigint DEFAULT NULL,
  product_id bigint DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE cart_products
ADD CONSTRAINT FKbilp3o9irlsvmbot68kfpthom FOREIGN KEY (cart_id)
REFERENCES carts (id);

--
-- Create foreign key
--
ALTER TABLE cart_products
ADD CONSTRAINT FKdayy17at10up1qqwlri9cocb3 FOREIGN KEY (product_id)
REFERENCES products (id);

--
-- Create table `hibernate_sequence`
--
CREATE TABLE hibernate_sequence (
  next_val bigint DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table address
--
-- Table ecomm_services.address does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'usuario1@gmail.com', '$2a$10$.fHQuWa5Af1HtpJFK2qXv.7xoWnqE0hyugpao21a.iCs27vHTvo7y', 'usuario1', NULL, NULL, NULL);

-- 
-- Dumping data for table orders
--
-- Table ecomm_services.orders does not contain any data (it is empty)

-- 
-- Dumping data for table products
--
INSERT INTO products VALUES
(1, 'Melhor cadeira de todas', 'Cadeira Gamex UltraX', 899.9, 10),
(2, 'Melhor carro de todos os tempos', 'HB20S 0 KM', 50000.99, 2),
(3, 'É uma casa em tamanho real', 'Casa da Barbie', 1000000.2, 3),
(4, '', 'Playstation 5', 3699.98, 4),
(5, '', 'Xbox 360', 230.59, 0);

-- 
-- Dumping data for table carts
--
INSERT INTO carts VALUES
(2, 1);

-- 
-- Dumping data for table order_products
--
-- Table ecomm_services.order_products does not contain any data (it is empty)

-- 
-- Dumping data for table hibernate_sequence
--
INSERT INTO hibernate_sequence VALUES
(3),
(3),
(3),
(3);

-- 
-- Dumping data for table cart_products
--
-- Table ecomm_services.cart_products does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;